name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    - name: Setup caching
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack
    - name: Run test
      run: stack test
